packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - lefthook

catalogs:
  react19:
    "react": ^19.2.3
    "react-dom": ^19.2.3
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3 

  next:
    "next": ^16.1.0

  typescript:
    "typescript": 5.9.3
